#
# export WORKING_URL=questions.kennycallado.dev
# export WORKING_URL=localhost:8000

# 1 admin  
# 2 coord 
# 4 thera 
# 7 user  
#12 user 

GET http://localhost:8000/health

GET http://localhost:8001/health

GET http://localhost:8002/health

#GET https://questions.kennycallado.dev/auth/bypass/1
GET http://localhost:8002/auth/bypass/1
Accept: application/json

GET http://localhost:8000/api/v1/user
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/user/11
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/user
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "depends_on": 1,
  "role_id": 4,
  "active": false
}

GET http://localhost:8000/api/v1/user/12
Accept: application/json
Authorization: Bearer 

PUT http://localhost:8000/api/v1/user/12
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "depends_on": 4,
  "role_id": 4,
  "active": true,
  "fcm_token": "1234567890"
}

PATCH http://localhost:8000/api/v1/user/11/fcm
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "1234567890abcd"
}


#POST http://{{WORKING_URL}}/api/v1/auth/login
#POST http://localhost:8002/auth/login
POST https://questions.kennycallado.dev/auth/login
Accept: application/json
Content-Type: application/json

{
  "admin"
}
